services:
  - type: web
    name: gaa-studio-backend
    env: python
    region: oregon
    buildCommand: "pip install --no-cache-dir -r requirements.txt"
    startCommand: "gunicorn --bind 0.0.0.0:5000 app:app"
    envVars:
      - key: FIREBASE_TYPE
        value: service_account
      - key: FIREBASE_PROJECT_ID
        value: gaastudio-2a7ac
      - key: FIREBASE_PRIVATE_KEY_ID
        value: a10063e0b00b240e1683e66380a1f8db168ad6bd
      - key: FIREBASE_PRIVATE_KEY
        value: ${{ FIREBASE_PRIVATE_KEY }}
      - key: FIREBASE_CLIENT_EMAIL
        value: firebase-adminsdk-pxkjd@gaastudio-2a7ac.iam.gserviceaccount.com
      - key: FIREBASE_CLIENT_ID
        value: 100589804799267688451
      - key: FIREBASE_AUTH_URI
        value: https://accounts.google.com/o/oauth2/auth
      - key: FIREBASE_TOKEN_URI
        value: https://oauth2.googleapis.com/token
      - key: FIREBASE_AUTH_PROVIDER_CERT_URL
        value: https://www.googleapis.com/oauth2/v1/certs
      - key: FIREBASE_CLIENT_CERT_URL
        value: https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-pxkjd%40gaastudio-2a7ac.iam.gserviceaccount.com
      - key: FIREBASE_UNIVERSE_DOMAIN
        value: googleapis.com
    mounts:
      - type: bind
        source: ./backend
        target: /opt/render/project/src/backend


